### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#163]
# Problem

When I search for:
"Aguilla" I get 48 sites, 0 taxa. 
"Agulla" I get 0 sites, 0 taxa. 
"Auilla" I get 7 sites, 2 taxa.

When I search for the site:

"Malgas" I get 0 sites, 0 taxa.
"Breede" I get 0 sites, 0 taxa.

## Expected Behaviour

- I'm expecting 1 character to be within the fuzziness of the search to still be found.
- I'm expecting to find sites by name.

**Comment by cchristelis** [comment]
Also if I search for "Galaxias" I get 195 sites and when I select one of those sites I'm expecting to see the species list filtered by these, but what I do see is all the site's species listed. Filters and searches should apply while they are applied.

**Comment by dimasciput** [comment]
This ticket is too big, I will break it into three issues : 
- [ ] Fix search fuzziness https://github.com/kartoza/django-bims/issues/245
- [ ] Ability to search by site ( not implemented yet ) https://github.com/kartoza/django-bims/issues/275
- [ ] Filter species list in side panel https://github.com/kartoza/django-bims/issues/274

**Comment by cchristelis** [comment]
Since all the sub-issues have been closed from your comment @dimasciput, I'm closing this issue. @Vries14, could you confirm that the search is working as expected based on the original comment.

**Comment by dimasciput** [comment]
@Vries14 did you just test it? Probably because admire upload layers on the testing, making the server slow. Can you test it again later?

**Comment by Vries14** [comment]
- able to find sites by name
- search results based on characters within the search
- searching for species then clicking on sites, sites species filtered by search
